name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-upload-artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, linux]
        goarch: [amd64, arm64]
        include:
          - goos: darwin
            goarch: amd64
            os: macos-intel
          - goos: darwin
            goarch: arm64
            os: macos-apple-silicon
          - goos: linux
            goarch: amd64
            os: linux-intel
          - goos: linux
            goarch: arm64
            os: linux-arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.20'

    - name: Compile
      run: |
        env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/psh-${{ matrix.os }} .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-binary
        path: build/psh-${{ matrix.os }}

  create-release:
    needs: build-and-upload-artifacts
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download all artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: Check if release exists
      id: check_release
      run: |
        if gh release view ${{ github.ref }}; then
          echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
        else
          echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
        fi
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to existing release
      if: env.RELEASE_EXISTS == 'true'
      run: |
        gh release upload ${{ github.ref }} \
        artifacts/macos-intel-binary/psh-macos-intel \
        artifacts/macos-apple-silicon-binary/psh-macos-apple-silicon \
        artifacts/linux-intel-binary/psh-linux-intel \
        artifacts/linux-arm64-binary/psh-linux-arm64
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create new release
      if: env.RELEASE_EXISTS == 'false'
      run: |
        gh release create ${{ github.ref }} \
        artifacts/macos-intel-binary/psh-macos-intel \
        artifacts/macos-apple-silicon-binary/psh-macos-apple-silicon \
        artifacts/linux-intel-binary/psh-linux-intel \
        artifacts/linux-arm64-binary/psh-linux-arm64 \
        -t ${{ github.ref }} -n "Release ${{ github.ref }}"
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
